import {Seller} from "./seller";

export const SELLER:Seller[] = [
    {
        id: 1,
        name: "Pão de Açucar Santana",
        address: "R. Dr. César, 1234 - Santana, São Paulo - SP, 02013-004",
        size: "Grande",
        phone: "(11) 3055-6767",
        latitude: "-23.501463",
        longitude: "-46.637027",
        email: "santana@paodeacucar.com.br",
        pic: "./images/seller/pao-de-acucar-logo.jpg",
        thumb: "./images/seller/pao-de-acucar-thumb.jpg",
        price: '',
        deliver: '',
        fare: '',
        pickup:true,
        distance:''
    },
    {
        id: 2,
        name: "Oba Horti Fruti Santana",
        address: "R. Alfredo Pujol, 1324 - Santana, São Paulo - SP, 02017-003",
        size: "Médio",
        phone: "(11) 2971-8999",
        latitude: "-23.500005",
        longitude: "-46.638604",
        email: "santana@redeoba.com.br",
        pic: "./images/seller/oba-logo.jpg",
        thumb: "./images/seller/oba-thumb.jpg",
        price: '',
        deliver: '',
        fare: '',
        pickup:true,
        distance: ''
    },
    {
        id: 3,
        name: "Padaria Gran Royalle",
        address: "Av Bras Leme, 2327 - Santana, São Paulo - SP 02022-010",
        size: "Padaria",
        phone: "(11) 2959-1519",
        latitude: "-23.501379",
        longitude: "-46.639339",
        email: "santana@dia.com.br",
        pic: "./images/seller/gran-royalle.jpg",
        thumb: "./images/seller/gran-royalle-thumb.jpg",
        price: '',
        deliver: '',
        fare: '',
        pickup:true,
        distance: '0.1 km'
    },
    {
        id: 4,
        name: "Casa do supiro",
        address: "Rua Alfredo Pujol, 1260 - Santana, São Paulo - SP, 02017-004",
        size: "Mini",
        phone: "(11) 2971-3623",
        latitude: "-23.501740",
        longitude: "-46.637438",
        email: "casadosuspiro@gmail.com",
        pic: "./images/seller/casa-do-suspiro-logo.jpg",
        thumb: "./images/seller/casa-do-suspiro-thumb.jpg",
        price: '',
        deliver: '',
        fare: '',
        pickup:true ,
        distance: '0.3 km'
    } ,
    {
        id: 5,
        name: "Dia Santana",
        address: "Rua Alfredo Pujol, 1428 - Santana, São Paulo - SP, 02017-004",
        size: "Grande",
        phone: "(11) 4002-1080",
        latitude: "-23.501379",
        longitude: "-46.639339",
        email: "santana@dia.com.br",
        pic: "./images/seller/dia-logo.jpg",
        thumb: "./images/seller/dia-thumb.jpg",
        price: '',
        deliver: '',
        fare: '',
        pickup:true,
        distance: '0.5 km'
    },

];